# **Phish in the Web**
### **MLP Retrain**

**1. Data Preprocessing**


In [ ]:
#import libraries only ONCE
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler #no one hot // all columns numeric
from sklearn.model_selection import train_test_split #data splitting

In [ ]:
#read in data & check for shape
phish_df = pd.read_csv("Phishing_Legitimate_full.csv")
phish_df.shape

(10000, 50)

In [ ]:
#specifying the columns we want to keep
selected_columns = ['NumDots', 'SubdomainLevel', 'PathLevel', 'UrlLength', 'NumDash',
    'NumDashInHostname', 'AtSymbol','TildeSymbol', 'NumUnderscore','NumPercent',
    'NumQueryComponents','NumAmpersand','NumHash','NumNumericChars','NoHttps',
    'RandomString','IpAddress','DomainInSubdomains','DomainInPaths','HttpsInHostname','HostnameLength',
    'PathLength','QueryLength','DoubleSlashInPath','NumSensitiveWords','EmbeddedBrandName',
    'PctExtHyperlinks','PctExtResourceUrls','ExtFavicon','InsecureForms','RelativeFormAction',
    'ExtFormAction','AbnormalFormAction','PctNullSelfRedirectHyperlinks','FrequentDomainNameMismatch',
    'FakeLinkInStatusBar','RightClickDisabled','PopUpWindow','SubmitInfoToEmail','IframeOrFrame',
    'MissingTitle','ImagesOnlyInForm','SubdomainLevelRT','UrlLengthRT','PctExtResourceUrlsRT',
    'AbnormalExtFormActionR','ExtMetaScriptLinkRT','PctExtNullSelfRedirectHyperlinksRT', 'CLASS_LABEL']

#split the features into 5 - 10 - 15
ten_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle']

twenty_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel']

thirty_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT', 'IframeOrFrame', 'AbnormalFormAction', 'ExtFormAction',
                   'PctExtResourceUrlsRT', 'PctNullSelfRedirectHyperlinks']


#features
#feature_columns = ['NumDots', 'SubdomainLevel', 'PathLevel', 'UrlLength', 'NumDash', 'NumDashInHostname', 'AtSymbol','TildeSymbol', 'NumUnderscore','NumPercent','NumQueryComponents','NumAmpersand','NumHash','NumNumericChars','NoHttps','RandomString','IpAddress','DomainInSubdomains','DomainInPaths','HttpsInHostname','HostnameLength','PathLength','QueryLength','DoubleSlashInPath','NumSensitiveWords','EmbeddedBrandName','PctExtHyperlinks','PctExtResourceUrls','ExtFavicon','InsecureForms','RelativeFormAction', 'ExtFormAction','AbnormalFormAction','PctNullSelfRedirectHyperlinks','FrequentDomainNameMismatch','FakeLinkInStatusBar','RightClickDisabled','PopUpWindow','SubmitInfoToEmail','IframeOrFrame','MissingTitle','ImagesOnlyInForm','SubdomainLevelRT','UrlLengthRT','PctExtResourceUrlsRT','AbnormalExtFormActionR','ExtMetaScriptLinkRT','PctExtNullSelfRedirectHyperlinksRT']

#label
label_column = ['CLASS_LABEL']

In [ ]:
#initiate scaler
min_scaler = MinMaxScaler()

In [ ]:
#five features
phishing_10_features_df = phish_df[ten_features]

#ten features
phishing_20_features_df = phish_df[twenty_features]

#fifteen features
phishing_30_features_df = phish_df[thirty_features]

#label
phishing_label_df = phish_df[label_column]

#scale 10 features
phishing_10_features_df[ten_features] = min_scaler.fit_transform(phishing_10_features_df[ten_features])

#scale 20 features
phishing_20_features_df[twenty_features] = min_scaler.fit_transform(phishing_20_features_df[twenty_features])

#scale 30 features
phishing_30_features_df[thirty_features] = min_scaler.fit_transform(phishing_30_features_df[thirty_features])

#split data for 10 features into 70% train, 20% test, and 10% validation
x10_train, x10_temp, y10_train, y10_temp = train_test_split(phishing_10_features_df, phishing_label_df, test_size=0.3, random_state=42)
x10_val, x10_test, y10_val, y10_test = train_test_split(x10_temp, y10_temp, test_size=0.7, random_state=42)

#split data for 20 features into 70% train, 20% test, and 10% validation
x20_train, x20_temp, y20_train, y20_temp = train_test_split(phishing_20_features_df, phishing_label_df, test_size=0.3, random_state=42)
x20_val, x20_test, y20_val, y20_test = train_test_split(x20_temp, y20_temp, test_size=0.7, random_state=42)

#split data for 30 features into 70% train, 20% test, and 10% validation
x30_train, x30_temp, y30_train, y30_temp = train_test_split(phishing_30_features_df, phishing_label_df, test_size=0.3, random_state=42)
x30_val, x30_test, y30_val, y30_test = train_test_split(x30_temp, y30_temp, test_size=0.7, random_state=42)



<ipython-input-7-28374ad56c76>:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_10_features_df[ten_features] = min_scaler.fit_transform(phishing_10_features_df[ten_features])
<ipython-input-7-28374ad56c76>:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_20_features_df[twenty_features] = min_scaler.fit_transform(phishing_20_features_df[twenty_features])
<ipython-input-7-28374ad56c76>:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using

In [ ]:
#import necessary files
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report #report
from sklearn.metrics import roc_auc_score, confusion_matrix
from sklearn.metrics import accuracy_score

def print_evaluation_metrics(y_true, y_pred):
    print("ROC AUC Score:", roc_auc_score(y_true, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))


In [ ]:
#MLP (Multi-Layer Perceptron)
mlp10_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp10_model.fit(x10_train, y10_train.values.ravel())
mlp10_predictions = mlp10_model.predict(x10_test)

print("\nMLP Classification Report:")
print(classification_report(y10_test, mlp10_predictions))

# Calculate ROC AUC score
mlp10_roc_auc = roc_auc_score(y10_test, mlp10_predictions)
print("\nROC AUC Score:", mlp10_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y10_test, mlp10_predictions))

print()

#model's prediction 10 features
pred10 = mlp10_model.predict(x10_test)

#test accuracy of our model // import in the beginning
pred10_classes = np.round(pred10)
accuracy10 = accuracy_score(y10_test,pred10_classes)
accuracy10_perc = accuracy10 * 100
print (f"test accuracy = {accuracy10_perc:.2f}%")


MLP Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.95      0.93      1037
           1       0.94      0.91      0.93      1063

    accuracy                           0.93      2100
   macro avg       0.93      0.93      0.93      2100
weighted avg       0.93      0.93      0.93      2100


ROC AUC Score: 0.92595055387175

Confusion Matrix:
[[980  57]
 [ 99 964]]

test accuracy = 92.57%


In [ ]:
#MLP (Multi-Layer Perceptron)
mlp20_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp20_model.fit(x20_train, y20_train.values.ravel())
mlp20_predictions = mlp20_model.predict(x20_test)

print("\nMLP Classification Report:")
print(classification_report(y20_test, mlp20_predictions))

# Calculate ROC AUC score
mlp20_roc_auc = roc_auc_score(y20_test, mlp20_predictions)
print("\nROC AUC Score:", mlp20_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y20_test, mlp20_predictions))

print()

#model's prediction 15 features
pred20 = mlp20_model.predict(x20_test)

#test accuracy of our model // import in the beginning
pred20_classes = np.round(pred20)
accuracy20 = accuracy_score(y20_test,pred20_classes)
accuracy20_perc = accuracy20 * 100
print (f"test accuracy = {accuracy20_perc:.2f}%")


MLP Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.98      0.96      1037
           1       0.98      0.94      0.96      1063

    accuracy                           0.96      2100
   macro avg       0.96      0.96      0.96      2100
weighted avg       0.96      0.96      0.96      2100


ROC AUC Score: 0.9597239849010869

Confusion Matrix:
[[1012   25]
 [  60 1003]]

test accuracy = 95.95%


In [ ]:
#MLP (Multi-Layer Perceptron)
mlp30_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp30_model.fit(x30_train, y30_train.values.ravel())
mlp30_predictions = mlp30_model.predict(x30_test)

print("\nMLP Classification Report:")
print(classification_report(y30_test, mlp30_predictions))

# Calculate ROC AUC score
mlp30_roc_auc = roc_auc_score(y30_test, mlp30_predictions)
print("\nROC AUC Score:", mlp30_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y30_test, mlp30_predictions))

#model's prediction 15 features
pred30 = mlp30_model.predict(x30_test)

#test accuracy of our model // import in the beginning
pred30_classes = np.round(pred30)
accuracy30 = accuracy_score(y30_test,pred30_classes)
accuracy30_perc = accuracy30 * 100
print (f"test accuracy = {accuracy30_perc:.2f}%")


MLP Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.97      0.97      1037
           1       0.97      0.98      0.98      1063

    accuracy                           0.98      2100
   macro avg       0.98      0.98      0.98      2100
weighted avg       0.98      0.98      0.98      2100


ROC AUC Score: 0.9752225057627881

Confusion Matrix:
[[1010   27]
 [  25 1038]]
test accuracy = 97.52%


In [ ]:
thirty1_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT', 'IframeOrFrame', 'AbnormalFormAction', 'ExtFormAction',
                   'PctExtResourceUrlsRT', 'PctNullSelfRedirectHyperlinks', 'EmbeddedBrandName']

#label
label_column = ['CLASS_LABEL']

#fifteen features
phishing_31_features_df = phish_df[thirty1_features]

#label
phishing_label_df = phish_df[label_column]

#scale 5 features
phishing_31_features_df[thirty1_features] = min_scaler.fit_transform(phishing_31_features_df[thirty1_features])

#split data!
x31_train, x31_temp, y31_train, y31_temp = train_test_split(phishing_31_features_df, phishing_label_df, test_size=0.3, random_state=42)
x31_val, x31_test, y31_val, y31_test = train_test_split(x31_temp, y31_temp, test_size=0.7, random_state=42)

#MLP (Multi-Layer Perceptron)
mlp31_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp31_model.fit(x31_train, y31_train.values.ravel())
mlp31_predictions = mlp31_model.predict(x31_test)

print("\nMLP Classification Report:")
print(classification_report(y31_test, mlp31_predictions))

# Calculate ROC AUC score
mlp31_roc_auc = roc_auc_score(y31_test, mlp31_predictions)
print("\nROC AUC Score:", mlp31_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y31_test, mlp31_predictions))

#model's prediction 15 features
pred31 = mlp31_model.predict(x31_test)

#test accuracy of our model // import in the beginning
pred31_classes = np.round(pred31)
accuracy31 = accuracy_score(y31_test,pred31_classes)
accuracy31_perc = accuracy31 * 100
print (f"test accuracy = {accuracy31_perc:.2f}%")

<ipython-input-12-536586222223>:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_31_features_df[thirty1_features] = min_scaler.fit_transform(phishing_31_features_df[thirty1_features])



MLP Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.97      0.98      1037
           1       0.97      0.98      0.98      1063

    accuracy                           0.98      2100
   macro avg       0.98      0.98      0.98      2100
weighted avg       0.98      0.98      0.98      2100


ROC AUC Score: 0.975681079457985

Confusion Matrix:
[[1009   28]
 [  23 1040]]
test accuracy = 97.57%


In [ ]:
thirty2_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT', 'IframeOrFrame', 'AbnormalFormAction', 'ExtFormAction',
                   'PctExtResourceUrlsRT', 'PctNullSelfRedirectHyperlinks', 'EmbeddedBrandName', 'DomainInPaths']

#label
label_column = ['CLASS_LABEL']

#fifteen features
phishing_32_features_df = phish_df[thirty2_features]

#label
phishing_label_df = phish_df[label_column]

#scale 5 features
phishing_32_features_df[thirty2_features] = min_scaler.fit_transform(phishing_32_features_df[thirty2_features])

#split data!
x32_train, x32_temp, y32_train, y32_temp = train_test_split(phishing_32_features_df, phishing_label_df, test_size=0.3, random_state=42)
x32_val, x32_test, y32_val, y32_test = train_test_split(x32_temp, y32_temp, test_size=0.7, random_state=42)

#MLP (Multi-Layer Perceptron)
mlp32_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp32_model.fit(x32_train, y32_train.values.ravel())
mlp32_predictions = mlp32_model.predict(x32_test)

print("\nMLP Classification Report:")
print(classification_report(y32_test, mlp32_predictions))

# Calculate ROC AUC score
mlp32_roc_auc = roc_auc_score(y32_test, mlp32_predictions)
print("\nROC AUC Score:", mlp32_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y32_test, mlp32_predictions))

#model's prediction 15 features
pred32 = mlp32_model.predict(x32_test)

#test accuracy of our model // import in the beginning
pred32_classes = np.round(pred32)
accuracy32 = accuracy_score(y32_test,pred32_classes)
accuracy32_perc = accuracy32 * 100
print (f"test accuracy = {accuracy32_perc:.2f}%")

<ipython-input-13-f0922bdf0864>:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_32_features_df[thirty2_features] = min_scaler.fit_transform(phishing_32_features_df[thirty2_features])



MLP Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      1037
           1       0.98      0.97      0.97      1063

    accuracy                           0.97      2100
   macro avg       0.97      0.97      0.97      2100
weighted avg       0.97      0.97      0.97      2100


ROC AUC Score: 0.9743171515633688

Confusion Matrix:
[[1013   24]
 [  30 1033]]
test accuracy = 97.43%


In [ ]:
thirty3_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT', 'IframeOrFrame', 'AbnormalFormAction', 'ExtFormAction',
                   'PctExtResourceUrlsRT', 'PctNullSelfRedirectHyperlinks', 'EmbeddedBrandName', 'DomainInPaths',
                    'AbnormalExtFormActionR']

#label
label_column = ['CLASS_LABEL']

#fifteen features
phishing_33_features_df = phish_df[thirty3_features]

#label
phishing_label_df = phish_df[label_column]

#scale 5 features
phishing_33_features_df[thirty3_features] = min_scaler.fit_transform(phishing_33_features_df[thirty3_features])

#split data!
x33_train, x33_temp, y33_train, y33_temp = train_test_split(phishing_33_features_df, phishing_label_df, test_size=0.3, random_state=42)
x33_val, x33_test, y33_val, y33_test = train_test_split(x33_temp, y33_temp, test_size=0.7, random_state=42)

#MLP (Multi-Layer Perceptron)
mlp33_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp33_model.fit(x33_train, y33_train.values.ravel())
mlp33_predictions = mlp33_model.predict(x33_test)

print("\nMLP Classification Report:")
print(classification_report(y33_test, mlp33_predictions))

#calculate ROC AUC score
mlp33_roc_auc = roc_auc_score(y33_test, mlp33_predictions)
print("\nROC AUC Score:", mlp33_roc_auc)

#print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y33_test, mlp33_predictions))

#model's prediction 15 features
pred33 = mlp33_model.predict(x33_test)

#test accuracy of our model // import in the beginning
pred33_classes = np.round(pred33)
accuracy33 = accuracy_score(y33_test,pred33_classes)
accuracy33_perc = accuracy33 * 100
print (f"test accuracy = {accuracy33_perc:.2f}%")



<ipython-input-14-12947fbac38d>:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_33_features_df[thirty3_features] = min_scaler.fit_transform(phishing_33_features_df[thirty3_features])



MLP Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1037
           1       0.98      0.97      0.98      1063

    accuracy                           0.98      2100
   macro avg       0.98      0.98      0.98      2100
weighted avg       0.98      0.98      0.98      2100


ROC AUC Score: 0.976727951949097

Confusion Matrix:
[[1018   19]
 [  30 1033]]
test accuracy = 97.67%


In [ ]:
#features list
thirty4_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT', 'IframeOrFrame', 'AbnormalFormAction', 'ExtFormAction',
                   'PctExtResourceUrlsRT', 'PctNullSelfRedirectHyperlinks', 'EmbeddedBrandName', 'DomainInPaths',
                    'AbnormalExtFormActionR', 'ImagesOnlyInForm']

#label
label_column = ['CLASS_LABEL']

#select 34 features
phishing_34_features_df = phish_df[thirty4_features]

#label
phishing_label_df = phish_df[label_column]

#scale 34 features
phishing_34_features_df[thirty4_features] = min_scaler.fit_transform(phishing_34_features_df[thirty4_features])

#split data
x34_train, x34_temp, y34_train, y34_temp = train_test_split(phishing_34_features_df, phishing_label_df, test_size=0.3, random_state=42)
x34_val, x34_test, y34_val, y34_test = train_test_split(x34_temp, y34_temp, test_size=0.7, random_state=42)

#MLP (Multi-Layer Perceptron)
mlp34_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp34_model.fit(x34_train, y34_train.values.ravel())
mlp34_predictions = mlp34_model.predict(x34_test)

print("\nMLP Classification Report:")
print(classification_report(y34_test, mlp34_predictions))

#calculate ROC AUC score
mlp34_roc_auc = roc_auc_score(y34_test, mlp34_predictions)
print("\nROC AUC Score:", mlp34_roc_auc)

#print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y34_test, mlp34_predictions))

#model's prediction 34 features
pred34 = mlp34_model.predict(x34_test)

#test accuracy of our model
pred34_classes = np.round(pred34)
accuracy34 = accuracy_score(y34_test,pred34_classes)
accuracy34_perc = accuracy34 * 100
print (f"Test accuracy = {accuracy34_perc:.2f}%")


<ipython-input-15-36919535450d>:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_34_features_df[thirty4_features] = min_scaler.fit_transform(phishing_34_features_df[thirty4_features])



MLP Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1037
           1       0.98      0.98      0.98      1063

    accuracy                           0.98      2100
   macro avg       0.98      0.98      0.98      2100
weighted avg       0.98      0.98      0.98      2100


ROC AUC Score: 0.9790679931889786

Confusion Matrix:
[[1017   20]
 [  24 1039]]
Test accuracy = 97.90%


**overfit/underfit**

 we chose 34 features as precision and recall both reached 98% accuracy on their predictions.

In [ ]:
#best # of features was 34
mlp_val_predictions = mlp34_model.predict(x34_val)

print("MLP Validation Classification Report:")
print(classification_report(y34_val, mlp_val_predictions))

print("\nMLP Validation Evaluation Metrics:")
print_evaluation_metrics(y34_val, mlp_val_predictions)


MLP Validation Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       426
           1       0.99      0.98      0.98       474

    accuracy                           0.98       900
   macro avg       0.98      0.98      0.98       900
weighted avg       0.98      0.98      0.98       900


MLP Validation Evaluation Metrics:
ROC AUC Score: 0.9801806620312592
Confusion Matrix:
 [[419   7]
 [ 11 463]]
