# **Phish in the Web**
### **MLP Retrain**

**Data Preprocessing**

In [1]:
#import libraries only ONCE
import pandas as pd
from sklearn.preprocessing import MinMaxScaler #no one hot // all columns numeric
from sklearn.model_selection import train_test_split #data splitting

In [2]:
#read in data & check for shape
phish_df = pd.read_csv("Phishing_Legitimate_full.csv")
phish_df.shape

(10000, 50)

In [3]:
#specifying the columns we want to keep
selected_columns = ['NumDots', 'SubdomainLevel', 'PathLevel', 'UrlLength', 'NumDash',
    'NumDashInHostname', 'AtSymbol','TildeSymbol', 'NumUnderscore','NumPercent',
    'NumQueryComponents','NumAmpersand','NumHash','NumNumericChars','NoHttps',
    'RandomString','IpAddress','DomainInSubdomains','DomainInPaths','HttpsInHostname','HostnameLength',
    'PathLength','QueryLength','DoubleSlashInPath','NumSensitiveWords','EmbeddedBrandName',
    'PctExtHyperlinks','PctExtResourceUrls','ExtFavicon','InsecureForms','RelativeFormAction',
    'ExtFormAction','AbnormalFormAction','PctNullSelfRedirectHyperlinks','FrequentDomainNameMismatch',
    'FakeLinkInStatusBar','RightClickDisabled','PopUpWindow','SubmitInfoToEmail','IframeOrFrame',
    'MissingTitle','ImagesOnlyInForm','SubdomainLevelRT','UrlLengthRT','PctExtResourceUrlsRT',
    'AbnormalExtFormActionR','ExtMetaScriptLinkRT','PctExtNullSelfRedirectHyperlinksRT', 'CLASS_LABEL']

#split the features into 5 - 10 - 15
five_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls']

ten_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle']

fifteen_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars']

#features
#feature_columns = ['NumDots', 'SubdomainLevel', 'PathLevel', 'UrlLength', 'NumDash', 'NumDashInHostname', 'AtSymbol','TildeSymbol', 'NumUnderscore','NumPercent','NumQueryComponents','NumAmpersand','NumHash','NumNumericChars','NoHttps','RandomString','IpAddress','DomainInSubdomains','DomainInPaths','HttpsInHostname','HostnameLength','PathLength','QueryLength','DoubleSlashInPath','NumSensitiveWords','EmbeddedBrandName','PctExtHyperlinks','PctExtResourceUrls','ExtFavicon','InsecureForms','RelativeFormAction', 'ExtFormAction','AbnormalFormAction','PctNullSelfRedirectHyperlinks','FrequentDomainNameMismatch','FakeLinkInStatusBar','RightClickDisabled','PopUpWindow','SubmitInfoToEmail','IframeOrFrame','MissingTitle','ImagesOnlyInForm','SubdomainLevelRT','UrlLengthRT','PctExtResourceUrlsRT','AbnormalExtFormActionR','ExtMetaScriptLinkRT','PctExtNullSelfRedirectHyperlinksRT']

#label
label_column = ['CLASS_LABEL']

In [4]:
#five features
phishing_5_features_df = phish_df[five_features]

#ten features
phishing_10_features_df = phish_df[ten_features]

#fifteen features
phishing_15_features_df = phish_df[fifteen_features]

#label
phishing_label_df = phish_df[label_column]

### **feature engineering**

In [6]:
#initiate scaler
min_scaler = MinMaxScaler()

#scale 5 features
phishing_5_features_df[five_features] = min_scaler.fit_transform(phishing_5_features_df[five_features])

#scale 10 features
phishing_10_features_df[ten_features] = min_scaler.fit_transform(phishing_10_features_df[ten_features])

#scale 15 features
phishing_15_features_df[fifteen_features] = min_scaler.fit_transform(phishing_15_features_df[fifteen_features])

<ipython-input-6-cc977474be56>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_5_features_df[five_features] = min_scaler.fit_transform(phishing_5_features_df[five_features])
<ipython-input-6-cc977474be56>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_10_features_df[ten_features] = min_scaler.fit_transform(phishing_10_features_df[ten_features])
<ipython-input-6-cc977474be56>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[ro

### **data splitting**

In [7]:
#data splitting

#split data!
x5_train, x5_test, y5_train, y5_test = train_test_split(phishing_5_features_df, phishing_label_df, test_size=0.2, random_state=42)

#split data!
x10_train, x10_test, y10_train, y10_test = train_test_split(phishing_10_features_df, phishing_label_df, test_size=0.2, random_state=42)

#split data!
x15_train, x15_test, y15_train, y15_test = train_test_split(phishing_15_features_df, phishing_label_df, test_size=0.2, random_state=42)

In [8]:
#print training data shape and label's shape (5 features)
print (f"Training: Features' shape [no. of examples * feature vector size] =  {x5_train.shape}")
print (f"Training: Label's shape [no. of examples * 1] = {y5_train.shape}\n")

#print test data shape and label's shape (5 features)
print (f"Test: Features' shape [no. of examples * feature vector size] =  {x5_test.shape}")
print (f"Test: Label's shape [no. of examples * 1] = {y5_test.shape}\n")

Training: Features' shape [no. of examples * feature vector size] =  (8000, 5)
Training: Label's shape [no. of examples * 1] = (8000, 1)

Test: Features' shape [no. of examples * feature vector size] =  (2000, 5)
Test: Label's shape [no. of examples * 1] = (2000, 1)



In [9]:
#print training data shape and label's shape (10 features)
print (f"Training: Features' shape [no. of examples * feature vector size] =  {x10_train.shape}")
print (f"Training: Label's shape [no. of examples * 1] = {y10_train.shape}\n")

#print test data shape and label's shape (10 features)
print (f"Test: Features' shape [no. of examples * feature vector size] =  {x10_test.shape}")
print (f"Test: Label's shape [no. of examples * 1] = {y10_test.shape}\n")

Training: Features' shape [no. of examples * feature vector size] =  (8000, 10)
Training: Label's shape [no. of examples * 1] = (8000, 1)

Test: Features' shape [no. of examples * feature vector size] =  (2000, 10)
Test: Label's shape [no. of examples * 1] = (2000, 1)



In [10]:
#print training data shape and label's shape (15 features)
print (f"Training: Features' shape [no. of examples * feature vector size] =  {x15_train.shape}")
print (f"Training: Label's shape [no. of examples * 1] = {y15_train.shape}\n")

#print test data shape and label's shape (15 features)
print (f"Test: Features' shape [no. of examples * feature vector size] =  {x15_test.shape}")
print (f"Test: Label's shape [no. of examples * 1] = {y15_test.shape}\n")

Training: Features' shape [no. of examples * feature vector size] =  (8000, 15)
Training: Label's shape [no. of examples * 1] = (8000, 1)

Test: Features' shape [no. of examples * feature vector size] =  (2000, 15)
Test: Label's shape [no. of examples * 1] = (2000, 1)



### **train mlp**

In [11]:
#import necessary files
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report #report
from sklearn.metrics import roc_auc_score, confusion_matrix


In [12]:
#MLP (Multi-Layer Perceptron)
mlp5_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp5_model.fit(x5_train, y5_train.values.ravel())
mlp5_predictions = mlp5_model.predict(x5_test)

print("\nMLP Classification Report:")
print(classification_report(y5_test, mlp5_predictions))

# Calculate ROC AUC score
mlp5_roc_auc = roc_auc_score(y5_test, mlp5_predictions)
print("\nROC AUC Score:", mlp5_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y5_test, mlp5_predictions))


MLP Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.88      0.91       988
           1       0.89      0.94      0.91      1012

    accuracy                           0.91      2000
   macro avg       0.91      0.91      0.91      2000
weighted avg       0.91      0.91      0.91      2000


ROC AUC Score: 0.9101570626170169

Confusion Matrix:
[[871 117]
 [ 62 950]]


In [13]:
#MLP (Multi-Layer Perceptron)
mlp10_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp10_model.fit(x10_train, y10_train.values.ravel())
mlp10_predictions = mlp10_model.predict(x10_test)

print("\nMLP Classification Report:")
print(classification_report(y10_test, mlp10_predictions))

# Calculate ROC AUC score
mlp10_roc_auc = roc_auc_score(y10_test, mlp10_predictions)
print("\nROC AUC Score:", mlp10_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y10_test, mlp10_predictions))


MLP Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.95      0.94       988
           1       0.95      0.94      0.94      1012

    accuracy                           0.94      2000
   macro avg       0.94      0.94      0.94      2000
weighted avg       0.94      0.94      0.94      2000


ROC AUC Score: 0.943063801187371

Confusion Matrix:
[[937  51]
 [ 63 949]]


In [14]:
#MLP (Multi-Layer Perceptron)
mlp15_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp15_model.fit(x15_train, y15_train.values.ravel())
mlp15_predictions = mlp15_model.predict(x15_test)

print("\nMLP Classification Report:")
print(classification_report(y15_test, mlp15_predictions))

# Calculate ROC AUC score
mlp15_roc_auc = roc_auc_score(y15_test, mlp15_predictions)
print("\nROC AUC Score:", mlp15_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y15_test, mlp15_predictions))


MLP Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       988
           1       0.95      0.95      0.95      1012

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000


ROC AUC Score: 0.9525111616072715

Confusion Matrix:
[[942  46]
 [ 49 963]]


### **model evaluation**

In [15]:
#import necessary files
from sklearn.metrics import accuracy_score
import numpy as np


In [16]:
#model's prediction 5 features
pred5 = mlp5_model.predict(x5_test)

#test accuracy of our model // import in the beginning
pred5_classes = np.round(pred5)
accuracy5 = accuracy_score(y5_test,pred5_classes)
accuracy5_perc = accuracy5 * 100
print (f"test accuracy = {accuracy5_perc:.2f}%")

test accuracy = 91.05%


In [17]:
#model's prediction 10 features
pred10 = mlp10_model.predict(x10_test)

#test accuracy of our model // import in the beginning
pred10_classes = np.round(pred10)
accuracy10 = accuracy_score(y10_test,pred10_classes)
accuracy10_perc = accuracy10 * 100
print (f"test accuracy = {accuracy10_perc:.2f}%")

test accuracy = 94.30%


In [18]:
#model's prediction 15 features
pred15 = mlp15_model.predict(x15_test)

#test accuracy of our model // import in the beginning
pred15_classes = np.round(pred15)
accuracy15 = accuracy_score(y15_test,pred15_classes)
accuracy15_perc = accuracy15 * 100
print (f"test accuracy = {accuracy15_perc:.2f}%")

test accuracy = 95.25%


### **Insights**

- [input here]

- I will be testing with more features to see where adding features will not improve accuracy

In [19]:
twenty_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel']

#label
label_column = ['CLASS_LABEL']

#fifteen features
phishing_20_features_df = phish_df[twenty_features]

#label
phishing_label_df = phish_df[label_column]

#scale 5 features
phishing_20_features_df[twenty_features] = min_scaler.fit_transform(phishing_20_features_df[twenty_features])

#split data!
x20_train, x20_test, y20_train, y20_test = train_test_split(phishing_20_features_df, phishing_label_df, test_size=0.2, random_state=42)


<ipython-input-19-d083b2bcf043>:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_20_features_df[twenty_features] = min_scaler.fit_transform(phishing_20_features_df[twenty_features])


In [20]:
#MLP (Multi-Layer Perceptron)
mlp20_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp20_model.fit(x20_train, y20_train.values.ravel())
mlp20_predictions = mlp20_model.predict(x20_test)

print("\nMLP Classification Report:")
print(classification_report(y20_test, mlp20_predictions))

# Calculate ROC AUC score
mlp20_roc_auc = roc_auc_score(y20_test, mlp20_predictions)
print("\nROC AUC Score:", mlp20_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y20_test, mlp20_predictions))


MLP Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       988
           1       0.97      0.97      0.97      1012

    accuracy                           0.97      2000
   macro avg       0.97      0.97      0.97      2000
weighted avg       0.97      0.97      0.97      2000


ROC AUC Score: 0.9699956793778304

Confusion Matrix:
[[958  30]
 [ 30 982]]


In [21]:
#model's prediction 15 features
pred20 = mlp20_model.predict(x20_test)

#test accuracy of our model // import in the beginning
pred20_classes = np.round(pred20)
accuracy20 = accuracy_score(y20_test,pred20_classes)
accuracy20_perc = accuracy20 * 100
print (f"test accuracy = {accuracy20_perc:.2f}%")

test accuracy = 97.00%


**25 features**

In [22]:
twenty5_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT']

#label
label_column = ['CLASS_LABEL']

#fifteen features
phishing_25_features_df = phish_df[twenty5_features]

#label
phishing_label_df = phish_df[label_column]

#scale 5 features
phishing_25_features_df[twenty5_features] = min_scaler.fit_transform(phishing_25_features_df[twenty5_features])

#split data!
x25_train, x25_test, y25_train, y25_test = train_test_split(phishing_25_features_df, phishing_label_df, test_size=0.2, random_state=42)


<ipython-input-22-c378d5eb4567>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_25_features_df[twenty5_features] = min_scaler.fit_transform(phishing_25_features_df[twenty5_features])


In [23]:
#MLP (Multi-Layer Perceptron)
mlp25_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp25_model.fit(x25_train, y25_train.values.ravel())
mlp25_predictions = mlp25_model.predict(x25_test)

print("\nMLP Classification Report:")
print(classification_report(y25_test, mlp25_predictions))

# Calculate ROC AUC score
mlp25_roc_auc = roc_auc_score(y25_test, mlp25_predictions)
print("\nROC AUC Score:", mlp25_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y25_test, mlp25_predictions))


MLP Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       988
           1       0.98      0.97      0.97      1012

    accuracy                           0.97      2000
   macro avg       0.97      0.97      0.97      2000
weighted avg       0.97      0.97      0.97      2000


ROC AUC Score: 0.9705617608935686

Confusion Matrix:
[[964  24]
 [ 35 977]]


In [24]:
#model's prediction 15 features
pred25 = mlp25_model.predict(x25_test)

#test accuracy of our model // import in the beginning
pred25_classes = np.round(pred25)
accuracy25 = accuracy_score(y25_test,pred25_classes)
accuracy25_perc = accuracy25 * 100
print (f"test accuracy = {accuracy25_perc:.2f}%")

test accuracy = 97.05%


**30 features**

In [26]:
thirty_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT', 'IframeOrFrame', 'AbnormalFormAction', 'ExtFormAction',
                   'PctExtResourceUrlsRT', 'PctNullSelfRedirectHyperlinks']

#label
label_column = ['CLASS_LABEL']

#fifteen features
phishing_30_features_df = phish_df[thirty_features]

#label
phishing_label_df = phish_df[label_column]

#scale 5 features
phishing_30_features_df[thirty_features] = min_scaler.fit_transform(phishing_30_features_df[thirty_features])

#split data!
x30_train, x30_test, y30_train, y30_test = train_test_split(phishing_30_features_df, phishing_label_df, test_size=0.2, random_state=42)

#MLP (Multi-Layer Perceptron)
mlp30_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp30_model.fit(x30_train, y30_train.values.ravel())
mlp30_predictions = mlp30_model.predict(x30_test)

print("\nMLP Classification Report:")
print(classification_report(y30_test, mlp30_predictions))

# Calculate ROC AUC score
mlp30_roc_auc = roc_auc_score(y30_test, mlp30_predictions)
print("\nROC AUC Score:", mlp30_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y30_test, mlp30_predictions))

#model's prediction 15 features
pred30 = mlp30_model.predict(x30_test)

#test accuracy of our model // import in the beginning
pred30_classes = np.round(pred30)
accuracy30 = accuracy_score(y30_test,pred30_classes)
accuracy30_perc = accuracy30 * 100
print (f"test accuracy = {accuracy30_perc:.2f}%")

<ipython-input-26-800497a135fe>:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_30_features_df[thirty_features] = min_scaler.fit_transform(phishing_30_features_df[thirty_features])



MLP Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.97      0.97       988
           1       0.97      0.98      0.98      1012

    accuracy                           0.97      2000
   macro avg       0.98      0.97      0.97      2000
weighted avg       0.98      0.97      0.97      2000


ROC AUC Score: 0.974936390840281

Confusion Matrix:
[[958  30]
 [ 20 992]]
test accuracy = 97.50%


**checking for 29, 31 features - where does it stop going up in accuracy?**

In [31]:
twenty9_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT', 'IframeOrFrame', 'AbnormalFormAction', 'ExtFormAction',
                   'PctExtResourceUrlsRT', 'PctNullSelfRedirectHyperlinks']

#label
label_column = ['CLASS_LABEL']

#fifteen features
phishing_29_features_df = phish_df[twenty9_features]

#label
phishing_label_df = phish_df[label_column]

#scale 5 features
phishing_29_features_df[twenty9_features] = min_scaler.fit_transform(phishing_29_features_df[twenty9_features])

#split data!
x29_train, x29_test, y29_train, y29_test = train_test_split(phishing_29_features_df, phishing_label_df, test_size=0.2, random_state=42)

#MLP (Multi-Layer Perceptron)
mlp29_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp29_model.fit(x29_train, y29_train.values.ravel())
mlp29_predictions = mlp29_model.predict(x29_test)

print("\nMLP Classification Report:")
print(classification_report(y29_test, mlp29_predictions))

# Calculate ROC AUC score
mlp29_roc_auc = roc_auc_score(y29_test, mlp20_predictions)
print("\nROC AUC Score:", mlp29_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y29_test, mlp29_predictions))

#model's prediction 15 features
pred29 = mlp29_model.predict(x29_test)

#test accuracy of our model // import in the beginning
pred29_classes = np.round(pred29)
accuracy29 = accuracy_score(y29_test,pred29_classes)
accuracy29_perc = accuracy29 * 100
print (f"test accuracy = {accuracy29_perc:.2f}%")

<ipython-input-31-6254aa786d4a>:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_29_features_df[twenty9_features] = min_scaler.fit_transform(phishing_29_features_df[twenty9_features])



MLP Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.97      0.97       988
           1       0.97      0.98      0.98      1012

    accuracy                           0.97      2000
   macro avg       0.98      0.97      0.97      2000
weighted avg       0.98      0.97      0.97      2000


ROC AUC Score: 0.9699956793778304

Confusion Matrix:
[[958  30]
 [ 20 992]]
test accuracy = 97.50%


In [30]:
thirty1_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT', 'IframeOrFrame', 'AbnormalFormAction', 'ExtFormAction',
                   'PctExtResourceUrlsRT', 'PctNullSelfRedirectHyperlinks', 'EmbeddedBrandName']

#label
label_column = ['CLASS_LABEL']

#fifteen features
phishing_31_features_df = phish_df[thirty1_features]

#label
phishing_label_df = phish_df[label_column]

#scale 5 features
phishing_31_features_df[thirty1_features] = min_scaler.fit_transform(phishing_31_features_df[thirty1_features])

#split data!
x31_train, x31_test, y31_train, y31_test = train_test_split(phishing_31_features_df, phishing_label_df, test_size=0.2, random_state=42)

#MLP (Multi-Layer Perceptron)
mlp31_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp31_model.fit(x31_train, y31_train.values.ravel())
mlp31_predictions = mlp31_model.predict(x31_test)

print("\nMLP Classification Report:")
print(classification_report(y31_test, mlp31_predictions))

# Calculate ROC AUC score
mlp31_roc_auc = roc_auc_score(y31_test, mlp31_predictions)
print("\nROC AUC Score:", mlp31_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y31_test, mlp31_predictions))

#model's prediction 15 features
pred31 = mlp31_model.predict(x31_test)

#test accuracy of our model // import in the beginning
pred31_classes = np.round(pred31)
accuracy31 = accuracy_score(y31_test,pred31_classes)
accuracy31_perc = accuracy31 * 100
print (f"test accuracy = {accuracy31_perc:.2f}%")

<ipython-input-30-abf092d6cd0c>:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_31_features_df[thirty1_features] = min_scaler.fit_transform(phishing_31_features_df[thirty1_features])



MLP Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.97      0.98       988
           1       0.98      0.98      0.98      1012

    accuracy                           0.98      2000
   macro avg       0.98      0.98      0.98      2000
weighted avg       0.98      0.98      0.98      2000


ROC AUC Score: 0.9754904706277704

Confusion Matrix:
[[963  25]
 [ 24 988]]
test accuracy = 97.55%


In [32]:
thirty2_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT', 'IframeOrFrame', 'AbnormalFormAction', 'ExtFormAction',
                   'PctExtResourceUrlsRT', 'PctNullSelfRedirectHyperlinks', 'EmbeddedBrandName', 'DomainInPaths']

#label
label_column = ['CLASS_LABEL']

#fifteen features
phishing_32_features_df = phish_df[thirty2_features]

#label
phishing_label_df = phish_df[label_column]

#scale 5 features
phishing_32_features_df[thirty2_features] = min_scaler.fit_transform(phishing_32_features_df[thirty2_features])

#split data!
x32_train, x32_test, y32_train, y32_test = train_test_split(phishing_32_features_df, phishing_label_df, test_size=0.2, random_state=42)

#MLP (Multi-Layer Perceptron)
mlp32_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp32_model.fit(x32_train, y32_train.values.ravel())
mlp32_predictions = mlp32_model.predict(x32_test)

print("\nMLP Classification Report:")
print(classification_report(y32_test, mlp32_predictions))

# Calculate ROC AUC score
mlp32_roc_auc = roc_auc_score(y32_test, mlp32_predictions)
print("\nROC AUC Score:", mlp32_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y32_test, mlp32_predictions))

#model's prediction 15 features
pred32 = mlp32_model.predict(x32_test)

#test accuracy of our model // import in the beginning
pred32_classes = np.round(pred32)
accuracy32 = accuracy_score(y32_test,pred32_classes)
accuracy32_perc = accuracy32 * 100
print (f"test accuracy = {accuracy32_perc:.2f}%")

<ipython-input-32-705c9bac4e4f>:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_32_features_df[thirty2_features] = min_scaler.fit_transform(phishing_32_features_df[thirty2_features])



MLP Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       988
           1       0.98      0.98      0.98      1012

    accuracy                           0.98      2000
   macro avg       0.98      0.98      0.98      2000
weighted avg       0.98      0.98      0.98      2000


ROC AUC Score: 0.9789729721079836

Confusion Matrix:
[[965  23]
 [ 19 993]]
test accuracy = 97.90%


In [33]:
thirty3_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT', 'IframeOrFrame', 'AbnormalFormAction', 'ExtFormAction',
                   'PctExtResourceUrlsRT', 'PctNullSelfRedirectHyperlinks', 'EmbeddedBrandName', 'DomainInPaths',
                    'AbnormalExtFormActionR']

#label
label_column = ['CLASS_LABEL']

#fifteen features
phishing_33_features_df = phish_df[thirty3_features]

#label
phishing_label_df = phish_df[label_column]

#scale 5 features
phishing_33_features_df[thirty3_features] = min_scaler.fit_transform(phishing_33_features_df[thirty3_features])

#split data!
x33_train, x33_test, y33_train, y33_test = train_test_split(phishing_33_features_df, phishing_label_df, test_size=0.2, random_state=42)

#MLP (Multi-Layer Perceptron)
mlp33_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp33_model.fit(x33_train, y33_train.values.ravel())
mlp33_predictions = mlp33_model.predict(x33_test)

print("\nMLP Classification Report:")
print(classification_report(y33_test, mlp33_predictions))

# Calculate ROC AUC score
mlp33_roc_auc = roc_auc_score(y33_test, mlp33_predictions)
print("\nROC AUC Score:", mlp33_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y33_test, mlp33_predictions))

#model's prediction 15 features
pred33 = mlp33_model.predict(x33_test)

#test accuracy of our model // import in the beginning
pred33_classes = np.round(pred33)
accuracy33 = accuracy_score(y33_test,pred33_classes)
accuracy33_perc = accuracy33 * 100
print (f"test accuracy = {accuracy33_perc:.2f}%")

<ipython-input-33-e74347c9fac8>:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_33_features_df[thirty3_features] = min_scaler.fit_transform(phishing_33_features_df[thirty3_features])



MLP Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       988
           1       0.97      0.99      0.98      1012

    accuracy                           0.98      2000
   macro avg       0.98      0.98      0.98      2000
weighted avg       0.98      0.98      0.98      2000


ROC AUC Score: 0.9794070346129843

Confusion Matrix:
[[960  28]
 [ 13 999]]
test accuracy = 97.95%


### **We found the maximum feature #'s!**

In [34]:
# Modify the features list
thirty4_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT', 'IframeOrFrame', 'AbnormalFormAction', 'ExtFormAction',
                   'PctExtResourceUrlsRT', 'PctNullSelfRedirectHyperlinks', 'EmbeddedBrandName', 'DomainInPaths',
                    'AbnormalExtFormActionR', 'ImagesOnlyInForm']

# Label
label_column = ['CLASS_LABEL']

# Select 34 features
phishing_34_features_df = phish_df[thirty4_features]

# Label
phishing_label_df = phish_df[label_column]

# Scale 34 features
phishing_34_features_df[thirty4_features] = min_scaler.fit_transform(phishing_34_features_df[thirty4_features])

# Split data
x34_train, x34_test, y34_train, y34_test = train_test_split(phishing_34_features_df, phishing_label_df, test_size=0.2, random_state=42)

# MLP (Multi-Layer Perceptron)
mlp34_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp34_model.fit(x34_train, y34_train.values.ravel())
mlp34_predictions = mlp34_model.predict(x34_test)

print("\nMLP Classification Report:")
print(classification_report(y34_test, mlp34_predictions))

# Calculate ROC AUC score
mlp34_roc_auc = roc_auc_score(y34_test, mlp34_predictions)
print("\nROC AUC Score:", mlp34_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y34_test, mlp34_predictions))

# Model's prediction 34 features
pred34 = mlp34_model.predict(x34_test)

# Test accuracy of our model
pred34_classes = np.round(pred34)
accuracy34 = accuracy_score(y34_test,pred34_classes)
accuracy34_perc = accuracy34 * 100
print (f"Test accuracy = {accuracy34_perc:.2f}%")


<ipython-input-34-dd989e3a4330>:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_34_features_df[thirty4_features] = min_scaler.fit_transform(phishing_34_features_df[thirty4_features])



MLP Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       988
           1       0.98      0.98      0.98      1012

    accuracy                           0.98      2000
   macro avg       0.98      0.98      0.98      2000
weighted avg       0.98      0.98      0.98      2000


ROC AUC Score: 0.9779968315437423

Confusion Matrix:
[[966  22]
 [ 22 990]]
Test accuracy = 97.80%


In [35]:
# Modify the features list
thirty5_features = ['PctExtHyperlinks', 'InsecureForms', 'FrequentDomainNameMismatch', 'NumPercent',
                 'PctExtResourceUrls','ExtFavicon', 'NumSensitiveWords', 'NoHttps', 'NumDots', 'MissingTitle',
                    'SubmitInfoToEmail', 'PopUpWindow', 'DoubleSlashInPath', 'IpAddress', 'NumNumericChars',
                   'PctExtNullSelfRedirectHyperlinksRT', 'SubdomainLevelRT', 'NumQueryComponents',
                   'NumUnderscore', 'SubdomainLevel', 'DomainInSubdomains', 'NumAmpersand', 'AtSymbol',
                    'ExtMetaScriptLinkRT', 'UrlLengthRT', 'IframeOrFrame', 'AbnormalFormAction', 'ExtFormAction',
                   'PctExtResourceUrlsRT', 'PctNullSelfRedirectHyperlinks', 'EmbeddedBrandName', 'DomainInPaths',
                    'AbnormalExtFormActionR', 'ImagesOnlyInForm', 'RightClickDisabled']

# Label
label_column = ['CLASS_LABEL']

# Select 35 features
phishing_35_features_df = phish_df[thirty5_features]

# Label
phishing_label_df = phish_df[label_column]

# Scale 35 features
phishing_35_features_df[thirty5_features] = min_scaler.fit_transform(phishing_35_features_df[thirty5_features])

# Split data
x35_train, x35_test, y35_train, y35_test = train_test_split(phishing_35_features_df, phishing_label_df, test_size=0.2, random_state=42)

# MLP (Multi-Layer Perceptron)
mlp35_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp35_model.fit(x35_train, y35_train.values.ravel())
mlp35_predictions = mlp35_model.predict(x35_test)

print("\nMLP Classification Report:")
print(classification_report(y35_test, mlp35_predictions))

# Calculate ROC AUC score
mlp35_roc_auc = roc_auc_score(y35_test, mlp35_predictions)
print("\nROC AUC Score:", mlp35_roc_auc)

# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y35_test, mlp35_predictions))

# Model's prediction 35 features
pred35 = mlp35_model.predict(x35_test)

# Test accuracy of our model
pred35_classes = np.round(pred35)
accuracy35 = accuracy_score(y35_test,pred35_classes)
accuracy35_perc = accuracy35 * 100
print (f"Test accuracy = {accuracy35_perc:.2f}%")


<ipython-input-35-5971bd171f6e>:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phishing_35_features_df[thirty5_features] = min_scaler.fit_transform(phishing_35_features_df[thirty5_features])



MLP Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       988
           1       0.97      0.98      0.97      1012

    accuracy                           0.97      2000
   macro avg       0.97      0.97      0.97      2000
weighted avg       0.97      0.97      0.97      2000


ROC AUC Score: 0.9744903266070315

Confusion Matrix:
[[962  26]
 [ 25 987]]
Test accuracy = 97.45%


### **Save best model**

- https://colab.research.google.com/drive/1X7W1qUBPVwXzZTaz8xJL4VKzrAVJ0-uU

- https://colab.research.google.com/drive/1HEM_HHScnqNRSyct544CcCob-0YraXEN#scrollTo=xrGmJi47GNAs



In [36]:
# Storing the model
import pickle

file_to_write = open("phishing_model.saved","wb")
pickle.dump(mlp33_model,file_to_write)
file_to_write.close()

# Let's also store our test data which we may need to use later
file_to_write = open("test_data.dat","wb")
pickle.dump([x33_test,y33_test],file_to_write)
file_to_write.close()

**load best model & test**

In [38]:
import pickle
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

model_file = open("phishing_model.saved","rb")
model = pickle.load(model_file)
model_file.close()

test_data_file = open("test_data.dat","rb")
x33_test,y33_test = pickle.load(test_data_file)
test_data_file.close()

# Test accuracy on our test dataset
y33_pred_test = model.predict(x33_test)

# Compute accuracy on test data
accuracy = accuracy_score(y33_pred_test, y33_test)

# Print accuracy on the test data

print (f"Accuracy on test data {accuracy}")

Accuracy on test data 0.9795
